[package]
name = "parversion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
simple-logging = "2.0.2"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
atty = "0.2"
clap = "3.0.0-beta.5"
regex= "1.10.3"
fancy-regex = "0.13.0"

[lib]
name = "parversion"
path = "src/lib.rs"
