[package]
name = "parversion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pandoculation = { git = "https://github.com/davidRoussov/pandoculation.git" }
log = "0.4"
simple-logging = "2.0.2"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
atty = "0.2"
clap = "3.0.0-beta.5"
regex= "1.10.3"
fancy-regex = "0.13.0"
html-escape = "0.2.13"
html-minifier = "5.0.0"
sha2 = "0.10.8"
sxd-xpath = "0.4.2"
xmltree = "0.10.3"
xml-rs = "0.8.20"
html5ever = "0.27.0"
markup5ever_rcdom = "0.3.0"

[lib]
name = "parversion"
path = "src/lib.rs"
