[package]
name = "parversion"
version = "0.1.0"
edition = "2021"

[dependencies]
pandoculation = { git = "https://github.com/davidRoussov/pandoculation.git" }
log = "0.4"
simple-logging = "2.0.2"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = {version = "1.0", features = ["derive", "rc"]}
serde_json = "1.0"
atty = "0.2"
clap = "3.0.0-beta.5"
regex= "1.10.3"
fancy-regex = "0.13.0"
sha2 = "0.10.8"
xmltree = "0.10.3"
xml-rs = "0.8.20"
html5ever = "0.27.0"
markup5ever_rcdom = "0.3.0"
sled = "0.34.7"
bincode = "1.3.3"
roxmltree = "0.19.0"
uuid = {version = "1.8.0", features = ["v4"]}
env_logger = "0.11.3"
dot = "0.1.4"
pathetic = "0.3.0"
url = "2.5.2"
scraper = "0.19.0"

[lib]
name = "parversion"
path = "src/lib.rs"
