[llm]
target_node_adjacent_xml_length = 2000
target_node_examples_max_count = 3

[llm.data_structure_interpretation]
enabled = true
target_node_adjacent_xml_length = 3000
target_node_examples_max_count = 10
